--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: supermario
  name: supermario
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: supermario
  template: 
    metadata: 
      labels: 
        app: supermario
    spec: 
      containers: 
        - 
          image: pengbai/docker-supermario
          name: supermario
          ports: 
            - 
              containerPort: 80
